# Generated by Django 3.1.3 on 2021-07-24 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0006_auto_20210623_1407'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Livestock_Inventory_Form',
        ),
    ]
