# Generated by Django 3.1.3 on 2021-07-24 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0007_delete_livestock_inventory_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livestock_Inventory_Form',
            fields=[
                ('vet_form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='portals.vet_forms')),
                ('farmer_username', models.CharField(max_length=12, verbose_name='Farmer Username')),
                ('species_targeted', models.CharField(choices=[('0', 'cattle'), ('1', 'sheep'), ('2', 'goat'), ('3', 'donkey'), ('4', 'dog'), ('5', 'horse'), ('6', 'poultry'), ('7', 'others')], default='0', max_length=20, verbose_name='Species targetted')),
                ('name_of_the_animal', models.CharField(blank=True, max_length=30, null=True, verbose_name='Name or identification number')),
                ('number_of_the_male_animals', models.IntegerField(blank=True, default=1, null=True, verbose_name='Number of male animals')),
                ('number_of_the_female_animals', models.IntegerField(blank=True, default=1, null=True, verbose_name='Number of female animals')),
                ('number_of_live_animals', models.IntegerField(blank=True, default=1, null=True, verbose_name='Number of live animals')),
                ('number_of_dead_animals', models.IntegerField(blank=True, default=1, null=True, verbose_name='Number of dead animals')),
                ('specify_the_cause_of_the_dead', models.CharField(blank=True, max_length=100, null=True, verbose_name='Specify the cause of dead')),
                ('is_your_animals_insured', models.CharField(choices=[('Y', 'yes'), ('N', 'no')], default='Y', max_length=20, verbose_name='Has your animals been insured?')),
                ('if_yes_give_insuring_company', models.CharField(blank=True, max_length=100, null=True, verbose_name='If yes,give the insuring company')),
                ('date_of_culling', models.DateField(verbose_name='Date of culling')),
                ('give_reason_for_culling', models.CharField(blank=True, max_length=200, null=True, verbose_name='Give reason for culling')),
                ('Attach_photos_of_your_animal', models.ImageField(default='default.jpg', upload_to='vet_photos', verbose_name='Upload photos')),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
