# Generated by Django 3.1.3 on 2021-07-24 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0008_livestock_inventory_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestock_inventory_form',
            name='Attach_photos_of_your_animal',
        ),
    ]
